spring.application.name=backend

# ===== Base de datos =====
spring.datasource.url=jdbc:mysql://localhost:3306/munaqfit?useSSL=false&serverTimezone=America/Lima&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===== JPA / Hibernate =====
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=true

# ===== JWT =====
app.jwt.secret=MUNAQFITSMANAGERSECRETKEY2026MUNAQFITSMANAGERSECRETKEY2026CHANGE_ME_IN_PRODUCTION
app.jwt.expiration-ms=86400000

# ===== Server =====
server.port=8080
server.error.include-message=always

# ===== Logs =====
logging.level.com.munaqfit.backend=DEBUG
